#!/usr/bin/env python3
#
# Adds DuckDuckGo bang as searchengine.
#
# Usage:
#   :spawn --userscript ripbang [bang]...
#
# Example:
#   :spawn --userscript ripbang amazon maps
#

from __future__ import print_function
import os, re, requests, sys

try:
    from urllib.parse import unquote
except ImportError:
    from urllib import unquote

for argument in sys.argv[1:]:
    bang = '!' + argument
    headers = {
        'User-Agent': 'AnythingButRequests'
    }
    r = requests.get('https://duckduckgo.com/',
                     params={'q': bang + ' SEARCHTEXT'},
                     headers=headers)

    searchengine = unquote(re.search("url=[^']+", r.text).group(0))
    searchengine = searchengine.replace('url=', '')
    searchengine = searchengine.replace('/l/?kh=-1&uddg=', '')
    searchengine = searchengine.replace('/l/?uddg=', '')
    searchengine = searchengine.replace('SEARCHTEXT', '{}')

    if os.getenv('QUTE_FIFO'):
        with open(os.environ['QUTE_FIFO'], 'w') as fifo:
            fifo.write(f'config-dict-add url.searchengines {bang} {searchengine}')
    else:
        # print('%s %s' % (bang, searchengine))
        print('set searchengines %s %s' % (bang, searchengine))
